### ISSUE TITLE
Alternative neat tabular alignment

### ISSUE THREAD

**Issue by eugenesvk** [geo-ant/roxygen#13]
Is it possible to use your approach to have this much better alignment of results and clean separation of code and documentation, i.e., treat **post**-argument doc comments as docs?:

```rs
fn sum_image_rows(       /// sum the rows of an image
  image_data: &    [f32],/// the image data in row-major format
  nrows     :       u32 ,/// the number of rows in the image
  ncols     :       u32 ,/// the number of columns in the image
  sums      : &mut [f32],/// an out buffer into which the resulting sums are placed. Must have space  for exactly `nrows` elements
) -> Result<(),String> {todo!()}
```

versus this messy mix where with many args you wouldn't even fit the view on a page
```rs
/// sum the rows of an image
fn sum_image_rows(
  /// the image data in row-major format
  image_data: &[f32],
  /// the number of rows in the image
  nrows: u32,
  /// the number of columns in the image
  ncols: u32,
  /// an out buffer into which the resulting
  /// sums are placed. Must have space 
  /// for exactly `nrows` elements
  sums: &mut [f32]) -> Result<(),String> {
    todo!()
} 
```

**Comment by geo-ant** [comment]
Hey, thanks for reaching out. I inadvertently removed a banner from this repo that indicates it's only passively maintained, so you couldn't have known that. I'll add the banner again later, sorry for that oversight. That means I'll fix bugs if they pop up, but other than that I don't really want to add major features.

At some point there might be an upstream rustdoc solution much better than what this little crate does. 

And to answer: sure, it's possible, but let me challenge the claim that the presented solution is objectively better. It's definitely a matter of taste, so reasonable people can disagree. To my mind, your proposal has a couple of big issues:

1. the placement of the docs is unidiomatic, cf. the way that struct fields are documented. A casual reader of your code (or possibly the rust formatter?) might assume that the comments are intended for different parameters than they actually are.
2. the function documentation itself is placed inside the parentheses which is extremely uniodiomatic. 
3. this tabular layout only works if you don't want to break lines at all. Breaking lines might be necessary in the top level function documentation (e.g. to add an example section). But breaking lines is also good for people like me who prefer a small width of code on screen.

**Comment by eugenesvk** [comment]
1+2 is about very bad current "idioms" hurting readability everywhere, so of course I'd love to improve them! Improving bad defaults is not a design issue!

1. Yes, struct fields have exactly the same issue - mixing docs and code, reducing readability, especially on long structs, but even on shorter ones - you can't properly align when everything is mixed
2. Same thing, I don't want to have uncollapsible wall of text obscuring functions! Why do you think docs.rs displays the description below function signatures when published, but forces you to put comments before in code???
3. It degrades with line breaks, but it's still better 

```rs
fn sum_image_rows(       /// sum the rows of an image
  image_data: &    [f32],/// the image data in row-major format
                         /// some extra text you feel must be on the second line
  /// ok, if you do this then it can become as bad as before, but only if you do this often
  nrows     :       u32 ,/// the number of rows in the image
```

> But breaking lines is also good for people like me who prefer a small width of code on screen

That's what dynamically toggleable word wrap is for! It fits your actual desired width. But if you hard break, then you force that small width everywhere - you can't as a reader dynamically change it

**Comment by geo-ant** [comment]
I didn't mean to say your points are invalid, I just have a different taste when it comes to formatting code. [You're not alone](https://github.com/rust-lang/rust/issues/57525#issuecomment-1300672144) with your idea of post-fix documentation.

Plus, this crate was never intended to change defaults of the language in any major way, but act as a polyfill for a small feature [that wasn't getting any traction](https://github.com/rust-lang/rust/issues/57525) in the upstream rustdoc.

Documenting function parameters is such a niche issue that I don't think it's worth (for me personally) to invest much more energy into the topic. I'm very happy with what the crate allows me to do. If you feel strongly about this, I invite you to fork the crate and implement your ideas, that's the beauty of open source :)

**Comment by geo-ant** [comment]
I'm going to close this issue here. If you decide to fork this crate and implement it yourself you can ping me if you run into trouble. What you want should be reasonably simple to implement: just extract the doc attributes and extract assign them to the previous function argument or the top level function. The one problem you might run into is that the last doc argument might not get parsed by the `syn` crate out of the box...

**Comment by geo-ant** [comment]
I'm going to close this issue here. If you decide to fork this crate and implement it yourself you can ping me if you run into trouble. What you want should be reasonably simple to implement: just extract the doc attributes and extract assign them to the previous function argument or the top level function. The one problem you might run into is that the last doc argument might not get parsed by the syn crate out of the box...

**Comment by eugenesvk** [comment]
Yes, the order/last item is exactly the issue I had in mind in my original question. Do you know how to resolve it? Or is it some deeper language limitation (how powerful is syn, can syn accept any invalid syntax and correct it at will?)

For now I've added a `///!` marker that splits the last valid comment (that belongs "natively" to the last argument) between the last and the previous argument

**Comment by eugenesvk** [comment]
By the way, is it possible to change the formatting of the output as well so that for short comments instead of having the whole section you could just amend the function signature with embedded comments, so `///` would simply turn into `//` in the output?

So the html would look something like:

pub fn sum_image_rows_pos( // sum the rows of an image
    image_data: &[[f32](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html)], // the image data in row-major format
    nrows: [u32](https://doc.rust-lang.org/1.82.0/std/primitive.u32.html), // the number of rows in the image
    ncols: [u32](https://doc.rust-lang.org/1.82.0/std/primitive.u32.html), // the number of columns in the image
    sums: &mut [[f32](https://doc.rust-lang.org/1.82.0/std/primitive.f32.html)],
) -> [Result](https://doc.rust-lang.org/1.82.0/core/result/enum.Result.html)<[()](https://doc.rust-lang.org/1.82.0/std/primitive.unit.html), [String](https://doc.rust-lang.org/1.82.0/alloc/string/struct.String.html)>
