### ISSUE TITLE
#[roxygen::parameters_section] seems to have no effect

### ISSUE THREAD

**Issue by eugenesvk** [geo-ant/roxygen#15]
I've tried the example from the Readme, and there is no difference if I add or remove `#[roxygen::parameters_section]`, the `Examples` is still shown before `Parameters:`

**Comment by geo-ant** [comment]
That shouldn't be, I'll take a look at it. Thanks for reporting!

**Comment by geo-ant** [comment]
I've just checked that I added a test for a case like this and the test does pass. So I'm wondering what's going wrong. I'll take a look tomorrow. You said you just used the code from the readme, right?

**Comment by eugenesvk** [comment]
Yes,

```rs
use roxygen::roxygen;

#[roxygen]
/// long documention
/// ...
#[roxygen::parameters_section]
/// # Examples
/// ...
fn foo(
  /// some docs
  first: i32,
  second: f32
  )
{}
```
